Adjustiiiiinnng

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -1,4 +1,4 @@
-name: Build and push container image
+name: Build and push foobar-api container image
 
 on:
   push:
@@ -20,32 +20,26 @@ jobs:
       # Checkout code
       - name: Checkout repository
         uses: actions/checkout@v3
+        with:
+          path: traefik-labs
 
       # Setup Go
       - name: Set up Go
         uses: actions/setup-go@v4
         with:
-          go-version: '1.22' 
+          go-version: '1.22'
 
-      # Cache Go modules
-      - name: Cache Go modules
-        uses: actions/cache@v3
-        with:
-          path: ~/go/pkg/mod
-          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
-          restore-keys: |
-            ${{ runner.os }}-go-
-
-      # Install dependencies
-      - name: Install dependencies
-        run: go mod download
-    
       # Check and run tests
       - name: Check and run tests
+        working-directory: traefik-labs/foobar-api
         run: |
+          if [ ! -f go.mod ] || [ ! -f go.sum ]; then
+            echo "Error: go.mod or go.sum not found!"
+            exit 1
+          fi
           TEST_FILES=$(find . -name "*_test.go")
           if [ -z "$TEST_FILES" ]; then
-             echo "Erro: Nenhum arquivo de teste encontrado!"
+             echo "Error: No test files found!"
              exit 1
           fi
           go test ./... -v
@@ -60,13 +54,16 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v3
 
-      # Kaniko to build and push the image
-      - name: Build and push with Kaniko
-        uses: aevea/kaniko-action@v1.1.0
+      # Substituir a seção Kaniko por Docker Build/Push
+      - name: Login to Docker Hub
+        uses: docker/login-action@v2
         with:
-          image: ${{ env.REGISTRY }}/${{ env.REGISTRY_USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
-          cache: true
-          cache-repository: ${{ env.REGISTRY }}/${{ env.REGISTRY_USER }}/${{ env.IMAGE_NAME }}-cache
-          executor: gcr.io/kaniko-project/executor:latest
+
+      - name: Build and push
+        uses: docker/build-push-action@v4
+        with:
+          context: ./foobar-api
+          push: true
+          tags: ${{ env.REGISTRY }}/${{ env.REGISTRY_USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
